# Generated by Django 4.2.16 on 2024-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependency',
            old_name='source_url',
            new_name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependency_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='install_command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='config_file',
            field=models.FileField(blank=True, null=True, upload_to='configs/'),
        ),
    ]
