# Generated by Django 4.2.16 on 2024-11-19 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_source_url_dependency_documentation_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='crawler.analyzedurl')),
            ],
        ),
    ]
